version: '3.8'
services:

  nats-service:
    image: nats:latest
    volumes:
      - ./nats/config/:/etc/nats
    command: "-c /etc/nats/nats.conf " 
    # --routes=nats://ruser:T0pS3cr3t@nats:6222" # --cluster nats://0.0.0.0:6222 " # "
    ports:
      - 4222:4222 # regular clients
      - 8222:8222 # http dashboard
      - 9222:6222 # websockets
    # network_mode: host

  bun-chat:
    build:
      context: ./chat-app
      dockerfile: Dockerfile    
    #container_name: bun-chat-dev
    volumes:
      #- ../../:workspaces:cached 
      # - .:/workspace:cached
      - .:my-app/workspace/chat-app/:cached
      #- .:/my-app/workspace:cached
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 5000:5000
      - 4223:4222
    links:
      - nats-service
    #command: bun --bun run dev ./my-app/
    command: /bin/sh -c "while sleep 1000; do :; done"
    # network_mode: host